const products = [
   {
      id: 1,
      title: "air force",
      company: "nike",
      image: "./images/nike-Airforce.jpg",
      price: 120.99,
   },
   {
      id: 2,
      title: "NMD R1",
      company: "adidas",
      image: "./images/adidas- NMD R1.jpg",
      price: 175.89,
   },
   {
      id: 3,
      title: "cartoon",
      company: "converse",
      image: "./images/converse- cartoon.jpg",
      price: 99.99,
   },
   {
      id: 4,
      title: "classic",
      company: "puma",
      image: "./images/puma- classic.jpg",
      price: 216.25,
   },
   {
      id: 5,
      title: "kaptir",
      company: "adidas",
      image: "./images/adidas- Kaptir.jpg",
      price: 82.99,
   },
   {
      id: 6,
      title: "jordan bred",
      company: "nike",
      image: "./images/nike- Jordan bred.jpg",
      price: 150.75,
   },
   {
      id: 7,
      title: "vintage",
      company: "converse",
      image: "./images/converse- vintage.jpg",
      price: 45.59,
   },
   {
      id: 8,
      title: "jordan 1",
      company: "nike",
      image: "./images/nike- Jordan 1.jpg",
      price: 220.99,
   },
   {
      id: 9,
      title: "red OG",
      company: "puma",
      image: "./images/puma- red OG.jpg",
      price: 81.99,
   },
   {
      id: 10,
      title: "air Max",
      company: "nike",
      image: "./images/nike-AirMax.jpg",
      price: 109.55,
   },
   {
      id: 11,
      title: "harden Vol. 4",
      company: "adidas",
      image: "./images/adidas- Harden.jpg",
      price: 129.98,
   },
   {
      id: 12,
      title: "runners",
      company: "nike",
      image: "./images/nike-runners.jpg",
      price: 45.99,
   },
   {
      id: 13,
      title: "all star - black",
      company: "converse",
      image: "./images/converse- allstar black.jpg",
      price: 101.99,
   },
   {
      id: 14,
      title: "jordan 4",
      company: "nike",
      image: "./images/nike- Jordan 4.jpg",
      price: 239.95,
   },
   {
      id: 15,
      title: "reinvention",
      company: "puma",
      image: "./images/puma- reinvention.jpg",
      price: 189.98,
   },
   {
      id: 16,
      title: "superstar",
      company: "adidas",
      image: "./images/adidas-superstar.jpg",
      price: 119.99,
   },
   {
      id: 17,
      title: "jordan 2",
      company: "nike",
      image: "./images/nike- Jordan 2.jpg",
      price: 139.95,
   },
   {
      id: 18,
      title: "all star - green",
      company: "converse",
      image: "./images/converse-allstar.jpg",
      price: 100.25,
   },
   {
      id: 19,
      title: "questar flow",
      company: "adidas",
      image: "./images/adidas-questar.jpg",
      price: 250.99,
   },
   {
      id: 20,
      title: "easy wear",
      company: "nike",
      image: "./images/nike-exercise.jpg",
      price: 50.69,
   },
   {
      id: 21,
      title: "slipstream leather",
      company: "puma",
      image: "./images/puma- Slipstream Leather.jpg",
      price: 89.99,
   },
];
